# commons
logging:
        com.ssafy.api: debug
        com.ssafy.core: debug
        org.hibernate.type.descriptor.sql: trace
spring:
    profiles:
        active: local
        include:
            - core
    # server port number
    server:
        port: 8888
    jwt:
        secret: secretKey
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties.hibernate:
            hbm2ddl.auto: update
            format_sql: true
            show_sql: true
            use_sql_comments: true
        generate-ddl: true
        open-in-view: false
    datasource:
        url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P11D102?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        driver-class-name: org.mariadb.jdbc.Driver
        username: S08P11D102
        password: ILwNR4FeeY
    flyway:
        enabled: false
    config:
        activate:
            on-profile: local

