# Real Server Configuration File
# Be careful on level

logging:
  level:
    root: warn
    com.ssafy.api: info
    org.hibernate.type.descriptor.sql: trace
spring:
  profiles:
    active: real
    include:
      - core
      - aws
  # Random Key
  jwt:
    secret: secretKey
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        # create(new table), update(add new column), none(nothing)
        hbm2ddl:
          auto: none
        format_sql: true
        show_sql: true
        use_sql_comments: true
    generate-ddl: true
    open-in-view: false
  datasource:
    url: mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P11D102?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
  flyway:
    enabled: false
  config:
    activate:
      on-profile: real
  servlet:
    multipart:
      file-size-threshold: 15MB
      # Path for saving upload file
      location: /home/
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 80
  domain: http://127.0.0.1
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

aes256:
  key: value

# Path json file for push alarm
app:
  firebase-config: key

# image request url for client
image:
  handler:
    url: /imae/upload/

# for sms
nurigo:
  api:
    key: value
    secretKey: secretKey
    sender: phoneNumber

# for payment
iamport:
  key: value
  secret: secretKey