# Real Server Configuration File
# Be careful on level

logging:
  level:
    root: warn
    com.ssafy: info
    com.ssafy.api: info
    org.hibernate.type.descriptor.sql: trace
    com.amazonaws.util.EC2MetadataUtils: error
spring:
  profiles:
    active: real
    include:
      - aws
      - coolsms
      - kakao
      - pay
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  # Random Key
  jwt:
    secret: DvqcGn8mnFjqSL4a
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      # create(new table), update(add new column), none(nothing)
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P12D102
    driver-class-name: org.mariadb.jdbc.Driver
    username: S08P12D102
    password: XVOdEsS6x3
    hikari:
      connection-timeout: 58000
      max-lifetime: 580000
  sql:
    init:
      mode: always
      continue-on-error: true
  redis:
    host: i8d102.p.ssafy.io
    port: 6379
server:
  port: 80
  domain: http://127.0.0.1
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728
