# Real Server Configuration File
# Be careful on level

logging:
  level:
    root: warn
    com.ssafy: info
    com.ssafy.api: info
    org.hibernate.type.descriptor.sql: trace
    com.amazonaws.util.EC2MetadataUtils: error
spring:
  profiles:
    active: real
    include:
      - aws
      - coolsms
      - login
      - pay
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      # create(new table), update(add new column), none(nothing)
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/smile?serverTimeZone=Asia/Seoul&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: S0706
    hikari:
      connection-timeout: 58000
      max-lifetime: 580000
  sql:
    init:
      mode: always
      continue-on-error: true
  redis:
    host: localhost
    port: 6379
server:
  port: 80
  domain: http://127.0.0.1
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728
